[project]
name = "my-ddpm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "iKlare", email = "iklare_hans@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
my-ddpm = "my_ddpm:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
